### PR TITLE
Remove Slim and make Stretch as latest version

### PR DESCRIPTION
**Pull request by radeno**
Ruby also removing Jessie and slim version, only supported Debian Stretch and Alpine.

Also advantage for Docker Ruby Node repository.
Less things to maintain.

### CODE REVIEW

**Review by Starefossen — APPROVED** [review]
LGTM

**Comment by Starefossen** [comment]
Great work @radeno! Feel free to merge this when you want 😄

**Comment by radeno** [comment]
Done :) You need to change paths in Docker Hub

**Comment by radeno** [comment]
Do you update docker hub generator please? "Slim" doesnt exists anymore and "latest" has bad path.

**Comment by Starefossen** [comment]
Fixed @radeno! Thanks for noticing 😄

**Pull request merged**
