### PR TITLE
Add combination 2-8

### PR DESCRIPTION
**Pull request by radeno**

### CODE REVIEW

**Review by Starefossen — APPROVED** [review]
LGTM 👍

**Comment by Starefossen** [comment]
I have added the `2-8` related tags and moved `latest`, `slim` and `alpine` to point to the new tags. Feel free to merge this whenever you like to @radeno 😄

**Comment by radeno** [comment]
Done :)

**Comment by Starefossen** [comment]
Thanks Radovan 😄

**Comment by Starefossen** [comment]
Btw. I have upgraded my Docker Hub subscription in order to speed up image builds.

**Comment by radeno** [comment]
You don't need to upgrade subscription.
There is problem only with Alpine repo, because compiling Node. Don't know why it takes so much time.

**Pull request merged**
