### PR TITLE
Slim version

### PR DESCRIPTION
**Pull request by radeno**
Due performance issues of musl in some cases. For example in Python or PHP should be 30% slower
https://superuser.com/questions/1219609/why-is-the-alpine-docker-image-over-50-slower-than-the-ubuntu-image/1234279

### CODE REVIEW

**Comment by Starefossen** [comment]
Can you rebase this on master as the 2-10 has been merged :) Thanks for the great work, @radeno!

**Comment by radeno** [comment]
Changes done :)

**Comment by airhorns** [comment]
ping @Starefossen this would be awesome to get merged!

**Comment by radeno** [comment]
@airhorns don't worry. i hope will be soon

**Comment by airhorns** [comment]
Ping @Starefossen ... any hope of getting this merged?

**Review by Starefossen — APPROVED** [review]

**Comment by Starefossen** [comment]
Sorry for the wait. I have merged and updated the tags in Docker Hub. Will take some time before all the builds complete.

**Pull request merged**
