### PR TITLE
Remove combination 2-4

### PR DESCRIPTION
**Pull request by radeno**

### CODE REVIEW

**Review by Starefossen — APPROVED** [review]
LGTM. Feel free to merge this when the tags have been removed from Docker Hub build settings.

**Comment by radeno** [comment]
Sure, but i need to access to Docker hub repo.

**Comment by Starefossen** [comment]
screen shot 2017-05-23 at 22 06 57

You should have access now, right?

**Comment by radeno** [comment]
I see i'm contributor, but without any permissions to edit.

**Comment by Starefossen** [comment]
Ugh! Stupid Docker Hub, there is no way to give admin rights.

**Comment by Starefossen** [comment]
I have removed the 2-4 related tags now. Feel free to merge.

**Comment by radeno** [comment]
Awww. Docker Hub.......

**Pull request merged**
